#!/usr/bin/env bash
# Shared session logging script for AI development tools
# Usage: session-logger.sh <tool-name> [additional-args...]

set -euo pipefail

# Configuration
SESSION_DIR=".ai-sessions"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Find the git root or use the project root
find_project_root() {
    local dir="$PROJECT_ROOT"
    while [[ "$dir" != "/" ]]; do
        if [[ -d "$dir/.git" ]]; then
            echo "$dir"
            return 0
        fi
        dir="$(dirname "$dir")"
    done
    echo "$PROJECT_ROOT"
}

# Generate a slug from the task title or prompt
generate_slug() {
    local text="${1:-session}"
    # Convert to lowercase, replace spaces/special chars with hyphens, truncate
    echo "$text" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//' | sed 's/-$//' | cut -c1-50
}

# Get changed files from git
get_changed_files() {
    local root="$1"
    if [[ -d "$root/.git" ]]; then
        cd "$root" && git diff --name-status HEAD~1 2>/dev/null || echo "Unable to determine changed files"
    else
        echo "Not a git repository"
    fi
}

# Main logging function
log_session() {
    local tool_name="${1:-unknown}"
    shift || true

    local root
    root="$(find_project_root)"
    local session_dir="$root/$SESSION_DIR"

    # Create session directory if it doesn't exist
    mkdir -p "$session_dir"

    # Generate filename with timestamp
    local timestamp
    timestamp="$(date '+%Y-%m-%d_%H-%M-%S')"
    local slug
    slug="$(generate_slug "${CLAUDE_SESSION_TITLE:-${GEMINI_SESSION_TITLE:-session}}")"
    local filename="${timestamp}_${slug}.md"
    local filepath="$session_dir/$filename"

    # Get environment variables that might contain session info
    local prompt="${CLAUDE_PROMPT:-${GEMINI_PROMPT:-${AI_PROMPT:-}}}"
    local model="${CLAUDE_MODEL:-${GEMINI_MODEL:-${AI_MODEL:-unknown}}}"
    local task_title="${CLAUDE_SESSION_TITLE:-${GEMINI_SESSION_TITLE:-${AI_TASK_TITLE:-Untitled Session}}}"

    # Get changed files
    local changed_files
    changed_files="$(get_changed_files "$root")"

    # Write session log
    cat > "$filepath" << EOF
# ${task_title}

**Date:** $(date '+%Y-%m-%d %H:%M:%S')
**Tool:** ${tool_name}
**Model:** ${model}

## Prompt
> ${prompt:-No prompt captured}

## Specification
<!-- AI-generated plan or specification -->
[Session specification not captured - add manually if needed]

## Files Changed
\`\`\`
${changed_files}
\`\`\`

## Outcome
<!-- Brief summary of what was accomplished -->
[Add session outcome summary here]

---
*This log was automatically generated by ai-dev-config session logger.*
EOF

    echo "Session logged to: $filepath"
}

# Export the function for use by other scripts
export -f log_session
export -f find_project_root
export -f generate_slug
export -f get_changed_files

# If script is run directly (not sourced), execute log_session
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    log_session "$@"
fi
